import postcss from 'postcss';
require("./fix-ugly-functions");
import imports from 'postcss-import';
import fixFontDeclarations from './fix-font-declarations';
import colorFunctions from './color-functions';
colorFunctions();
import gtkColorVariables from './color-variables';
import gtkPseudoClasses from './psuedo-classes';
import valueHook from './value-hook';

export default postcss([imports(), fixFontDeclarations, gtkColorVariables, gtkPseudoClasses, valueHook])
// Generated by CoffeeScript 2.2.3
/* (function() {
  var fixFontDeclarations, gtkColorVariables, gtkPseudoClasses, imports, postcss, valueHook;

  postcss = require("postcss");

  require("./fix-ugly-functions");

  imports = require("postcss-import");

  fixFontDeclarations = require("./fix-font-declarations");

  gtkColorVariables = require("./color-variables");

  require("./color-functions");

  gtkPseudoClasses = require("./psuedo-classes");

  valueHook = require("./value-hook");

  module.exports = postcss([imports(), fixFontDeclarations, gtkColorVariables, gtkPseudoClasses, valueHook]);

}).call(this); */
